version: '3.7'
services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - interim-sport-spa
      - interim-sport-root-spa
      - interim-sport-api
      - interim-sport-root-api
    networks:
      - back-tier

  interim-sport-spa:
    container_name: interim-sport-spa
    build: 
      context: ../interim-sport-spa
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ../interim-sport-spa/:/app/
    ports:
      - ${INTERIM_SPORT_SPA_PORT:-3000}:${INTERIM_SPORT_SPA_PORT:-3000}
    networks:
      - back-tier
    env_file:
      - ../interim-sport-spa/.env
    environment:
      PORT: ${INTERIM_SPORT_SPA_PORT:-3000}
      API_URL: http://0.0.0.0:${INTERIM_SPORT_API_PORT:-3335}

  interim-sport-api:
    container_name: interim-sport-api
    build: 
      context: ../interim-sport-api
      dockerfile: Dockerfile
    command: npm run start-dev
    volumes:
      - ../interim-sport-api/:/app/
    ports:
      - ${INTERIM_SPORT_API_PORT:-3335}:${INTERIM_SPORT_API_PORT:-3335}
    depends_on:
      - db
    networks:
      - back-tier
    env_file:
      - ../interim-sport-api/.env
    environment:
      HOST: 0.0.0.0
      PORT: ${INTERIM_SPORT_API_PORT:-3335}
      DB_HOST: db

  interim-sport-root-spa:
    container_name: interim-sport-root-spa
    build: 
      context: ../interim-sport-root-spa
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - ../interim-sport-root-spa/:/app/
    ports:
      - ${INTERIM_SPORT_ROOT_SPA_PORT:-3001}:${INTERIM_SPORT_ROOT_SPA_PORT:-3001}
    networks:
      - back-tier
    env_file:
      - ../interim-sport-root-spa/.env
    environment:
      API_URL: http://0.0.0.0:${INTERIM_SPORT_ROOT_API_PORT:-3333}
      REACT_APP_MESSENGER_SERVER: 0.0.0.0:${INTERIM_SPORT_MESSENGER_PORT:-3333}
      REACT_APP_MEDIA_URL: http://0.0.0.0:${INTERIM_SPORT_MEDIA_PORT:-3338}

  interim-sport-root-api:
    container_name: interim-sport-root-api
    build: 
      context: ../interim-sport-root-api
      dockerfile: Dockerfile
    command: >
      bash -c "npm run migrate
      && npm run seed 
      && npm run dev"
    volumes:
      - ../interim-sport-root-api/:/app/
    ports:
      - ${INTERIM_SPORT_ROOT_API_PORT:-3333}:${INTERIM_SPORT_ROOT_API_PORT:-3333}
    depends_on:
      - db
    networks:
      - back-tier
    env_file:
      - ../interim-sport-root-api/.env
    environment:
      HOST: 0.0.0.0
      PORT: ${INTERIM_SPORT_ROOT_API_PORT:-3333}
      APP_MEDIA_URL: http://0.0.0.0:${INTERIM_SPORT_MEDIA_PORT:-3338}
      FRONTEND_URL: http://0.0.0.0:${INTERIM_SPORT_SPA_PORT:-3000}
      DB_HOST: db

  interim-sport-media:
    container_name: interim-sport-media
    build: 
      context: ../interim-sport-media
      dockerfile: Dockerfile
    command: npm run start
    volumes:
      - media_assets:/app/public/
    ports:
      - ${INTERIM_SPORT_MEDIA_PORT:-3338}:${INTERIM_SPORT_MEDIA_PORT:-3338}
    depends_on:
      - db
    networks:
      - back-tier
    env_file:
      - ../interim-sport-media/.env
    environment:
      HOST: 0.0.0.0
      PORT: ${INTERIM_SPORT_MEDIA_PORT:-3338}
      DB_HOST: db

  interim-sport-messenger:
    container_name: interim-sport-messenger
    build: 
      context: ../interim-sport-messenger
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - ${INTERIM_SPORT_MESSENGER_PORT:-3334}:${INTERIM_SPORT_MESSENGER_PORT:-3334}
    depends_on:
      - db
    networks:
      - back-tier
    env_file:
      - ../interim-sport-messenger/.env
    environment:
      HOST: 0.0.0.0
      PORT: ${INTERIM_SPORT_MESSENGER_PORT:-3334}
      DB_HOST: db
      APP_MEDIA_URL: http://0.0.0.0:3334
      
  db:
    build: ./db
    container_name: db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - back-tier

volumes:
  media_assets:
  db-data: null

networks:
  back-tier: