version: '3.7'
services:
  interim-sport-spa:
    container_name: interim-sport-spa
    build: 
      context: ../interim-sport-spa
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ../interim-sport-spa/:/app/
    ports:
      - 3000:3000
    env_file:
      - ../interim-sport-spa/.env
    environment:
      PORT: 3000
      API_URL: http://0.0.0.0:3335

  interim-sport-api:
    container_name: interim-sport-api
    build: 
      context: ../interim-sport-api
      dockerfile: Dockerfile
    command: npm run start-dev
    volumes:
      - ../interim-sport-api/:/app/
    ports:
      - 3335:3335
    env_file:
      - ../interim-sport-api/.env
    environment:
      HOST: 0.0.0.0
      PORT: 3335
